/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Apsilankymo data
 */
export type Date = string | null;
/**
 * Apsilankymo laikas VV:MM
 */
export type Time = string | null;
/**
 * Įrašo numeris
 */
export type RecordNumber = string | null;
/**
 * Įrašo būsena
 */
export type Status = ("darbinis" | "galutinis") | null;
/**
 * Gydytojo vardas, pavardė ir pareigos
 */
export type Physician = string | null;
/**
 * Pagalbos tipas
 */
export type HelpType = ("butinoji" | "planine" | "kita") | null;
/**
 * Konsultacijos pobūdis
 */
export type ConsultationType = ("tiesioginis" | "nuotolinis" | "kitas") | null;
/**
 * Aptarnavimo ypatumai
 */
export type ServiceMethod = string | null;
/**
 * Ar atvyko su siuntimu
 */
export type ArrivedWithReferral = boolean | null;
/**
 * Siuntusios įstaigos pavadinimas
 */
export type ReferringInstitution = string | null;
/**
 * Siuntusio gydytojo vardas, pavardė
 */
export type ReferringPhysician = string | null;
/**
 * Siuntimo diagnozė su TLK-10-AM kodu
 */
export type ReferralDiagnosis = string | null;
/**
 * Ar atvežtas GMP
 */
export type ArrivedByAmbulance = boolean | null;
/**
 * GMP įstaigos pavadinimas
 */
export type AmbulanceInstitution = string | null;
/**
 * GMP nustatyta diagnozė
 */
export type AmbulanceDiagnosis = string | null;
/**
 * Diagnozių sąrašas su nuorodomis į transkripciją
 */
export type Items = DiagnosisItem[] | null;
/**
 * Diagnozė lietuvių kalba
 */
export type Diagnosis1 = string;
/**
 * TLK-10-AM kodas, pvz.: J45.0
 */
export type DiagnosisCode = string | null;
/**
 * Tikrumas: '+' patvirtinta, '-' atmesta, '0' įtariama
 */
export type DiagnosisCertainty = ("+" | "-" | "0") | null;
/**
 * Transkripcijos segmentų indeksai
 */
export type SourceSegments = number[];
/**
 * Gyvybinių rodiklių sąrašas su nuorodomis į transkripciją
 */
export type Items1 = VitalSignItem[] | null;
/**
 * Rodiklio pavadinimas
 */
export type Name = string;
/**
 * Rodiklio reikšmė su vienetais
 */
export type Value = string;
/**
 * Transkripcijos segmentų indeksai
 */
export type SourceSegments1 = number[];
/**
 * Kūno svoris kg
 */
export type Weight = number | null;
/**
 * Ūgis cm
 */
export type Height = number | null;
/**
 * Kūno masės indeksas kg/m². Norma: 18.5-24.9
 */
export type Bmi = number | null;
/**
 * Krūtinės apimtis cm
 */
export type ChestCircumference = number | null;
/**
 * Klubų apimtis cm
 */
export type HipCircumference = number | null;
/**
 * Juosmens apimtis cm
 */
export type WaistCircumference = number | null;
/**
 * Galvos apimtis cm
 */
export type HeadCircumference = number | null;
/**
 * Nusiskundimai ir anamnezė - atskiri teiginiai su nuorodomis
 */
export type ComplaintsAnamnesis = ClinicalStatement[] | null;
/**
 * Vienas klinikinis teiginys
 */
export type Statement = string;
/**
 * Transkripcijos segmentų indeksai, iš kurių išgautas teiginys
 */
export type SourceSegments2 = number[];
/**
 * Objektyvus būklės įvertinimas - atskiri teiginiai su nuorodomis
 */
export type ObjectiveCondition = ClinicalStatement[] | null;
/**
 * Planuojami tyrimai ir konsultacijos - atskiri teiginiai su nuorodomis
 */
export type TestsConsultationsPlan = ClinicalStatement[] | null;
/**
 * Atliktų tyrimų rezultatai - atskiri teiginiai su nuorodomis
 */
export type PerformedTestsConsultations = ClinicalStatement[] | null;
/**
 * Būklė konsultacijos pabaigoje - atskiri teiginiai su nuorodomis
 */
export type ConditionOnDischarge = ClinicalStatement[] | null;
/**
 * Papildoma informacija - atskiri teiginiai su nuorodomis
 */
export type Notes = ClinicalStatement[] | null;
/**
 * Gydymo veiksmų sąrašas su nuorodomis į transkripciją
 */
export type Items2 = TreatmentItem[] | null;
/**
 * Gydymo aprašymas
 */
export type Description = string;
/**
 * Gydymo tipas: 'medication', 'non_medication', 'prescription', 'referral', 'recommendation'
 */
export type Type = string;
/**
 * Transkripcijos segmentų indeksai
 */
export type SourceSegments3 = number[];
/**
 * Ar išduotas nedarbingumo pažymėjimas
 */
export type DisabilityCertificate = boolean | null;
/**
 * Ar išduotas nėštumo/gimdymo pažymėjimas
 */
export type MaternityCertificate = boolean | null;
/**
 * Ar išduota medicininė pažyma (094/a)
 */
export type MedicalCertificate = boolean | null;
/**
 * Pažymėjimo numeris
 */
export type DisabilityNumber = string | null;
/**
 * Nedarbingumo pradžios data
 */
export type DisabilityStartDate = string | null;
/**
 * Nedarbingumo pabaigos data
 */
export type DisabilityEndDate = string | null;
/**
 * Nedarbingumo priežasties aprašymas
 */
export type DisabilityDescription = string | null;
/**
 * Draudimas vairuoti
 */
export type CannotDrive = boolean | null;
/**
 * Draudimo vairuoti data
 */
export type CannotDriveDate = string | null;
/**
 * Draudimas naudoti ginklą
 */
export type CannotUseWeapon = boolean | null;
/**
 * Žinomos alergijos
 */
export type Allergies = Allergy[] | null;
/**
 * Alergijos tipas
 */
export type Type1 = "vaistai" | "maistas" | "kita";
/**
 * Alergeno aprašymas
 */
export type Description1 = string;
/**
 * Nustatymo data
 */
export type Date1 = string | null;
/**
 * Transkripcijos segmentų indeksai
 */
export type SourceSegments4 = number[];
/**
 * Atlikti skiepai
 */
export type Vaccinations = Vaccination[] | null;
/**
 * Skiepo pavadinimas | vakcinos pavadinimas
 */
export type Name1 = string;
/**
 * Skiepijimo data
 */
export type Date2 = string | null;
/**
 * Dot-notation path to the field, e.g., 'vital_signs.temperature'
 */
export type FieldName = string;
/**
 * The extracted value
 */
export type Value1 = string | number | boolean;
/**
 * Indices into the transcript array that support this extraction
 */
export type SourceSegments5 = number[];
/**
 * Confidence score for the extraction (0.0 to 1.0)
 */
export type Confidence = number | null;
/**
 * References linking extracted fields to source segments
 */
export type References = EntityReference[];

/**
 * Complete extraction result with document and references.
 */
export interface ExtractionResult {
  document: E025Document;
  references?: References;
}
/**
 * The extracted E025 document
 */
export interface E025Document {
  /**
   * Vizito metaduomenys (data, laikas, gydytojas)
   */
  visit?: VisitMetadata | null;
  /**
   * Siuntimo informacija
   */
  referral?: Referral | null;
  /**
   * GMP (greitosios) informacija
   */
  ambulance?: Ambulance | null;
  /**
   * Diagnozė (pagrindinė, kodai, tikrumas)
   */
  diagnosis?: Diagnosis | null;
  /**
   * Gyvybiniai rodikliai (temperatūra, spaudimas, pulsas ir kt.)
   */
  vital_signs?: VitalSigns | null;
  /**
   * Kūno matavimai (svoris, ūgis, apimtys)
   */
  body_measurements?: BodyMeasurements | null;
  /**
   * Klinikiniai užrašai (nusiskundimai, objektyvi būklė, tyrimų planas)
   */
  clinical_notes?: ClinicalNotes | null;
  /**
   * Gydymo informacija (vaistai, rekomendacijos)
   */
  treatment?: Treatment | null;
  /**
   * Pažymos ir nedarbingumo dokumentai
   */
  certificates?: Certificates | null;
  /**
   * Apribojimai (vairavimas, ginklai)
   */
  restrictions?: Restrictions | null;
  allergies?: Allergies;
  vaccinations?: Vaccinations;
}
/**
 * Vizito metaduomenys
 */
export interface VisitMetadata {
  date?: Date;
  time?: Time;
  record_number?: RecordNumber;
  status?: Status;
  physician?: Physician;
  help_type?: HelpType;
  consultation_type?: ConsultationType;
  service_method?: ServiceMethod;
}
/**
 * Siuntimo informacija
 */
export interface Referral {
  arrived_with_referral?: ArrivedWithReferral;
  referring_institution?: ReferringInstitution;
  referring_physician?: ReferringPhysician;
  referral_diagnosis?: ReferralDiagnosis;
}
/**
 * GMP (greitosios) informacija
 */
export interface Ambulance {
  arrived_by_ambulance?: ArrivedByAmbulance;
  ambulance_institution?: AmbulanceInstitution;
  ambulance_diagnosis?: AmbulanceDiagnosis;
}
/**
 * Diagnozės informacija - masyvas diagnozių su nuorodomis
 */
export interface Diagnosis {
  items?: Items;
}
/**
 * Individual diagnosis with transcript reference.
 */
export interface DiagnosisItem {
  diagnosis: Diagnosis1;
  diagnosis_code?: DiagnosisCode;
  diagnosis_certainty?: DiagnosisCertainty;
  source_segments?: SourceSegments;
}
/**
 * Gyvybiniai rodikliai - masyvas matavimų su nuorodomis
 */
export interface VitalSigns {
  items?: Items1;
}
/**
 * Individual vital sign measurement with transcript reference.
 */
export interface VitalSignItem {
  name: Name;
  value: Value;
  source_segments?: SourceSegments1;
}
/**
 * Kūno matavimai - svoris, ūgis, apimtys
 */
export interface BodyMeasurements {
  weight?: Weight;
  height?: Height;
  bmi?: Bmi;
  chest_circumference?: ChestCircumference;
  hip_circumference?: HipCircumference;
  waist_circumference?: WaistCircumference;
  head_circumference?: HeadCircumference;
}
/**
 * Klinikiniai užrašai ir tyrimai
 */
export interface ClinicalNotes {
  complaints_anamnesis?: ComplaintsAnamnesis;
  objective_condition?: ObjectiveCondition;
  tests_consultations_plan?: TestsConsultationsPlan;
  performed_tests_consultations?: PerformedTestsConsultations;
  condition_on_discharge?: ConditionOnDischarge;
  notes?: Notes;
}
/**
 * Individual clinical statement with transcript reference.
 */
export interface ClinicalStatement {
  statement: Statement;
  source_segments: SourceSegments2;
}
/**
 * Gydymo informacija - masyvas su nuorodomis
 */
export interface Treatment {
  items?: Items2;
}
/**
 * Individual treatment item with transcript reference.
 */
export interface TreatmentItem {
  description: Description;
  type: Type;
  source_segments?: SourceSegments3;
}
/**
 * Pažymos ir nedarbingumo dokumentai
 */
export interface Certificates {
  disability_certificate?: DisabilityCertificate;
  maternity_certificate?: MaternityCertificate;
  medical_certificate?: MedicalCertificate;
  disability_number?: DisabilityNumber;
  disability_start_date?: DisabilityStartDate;
  disability_end_date?: DisabilityEndDate;
  disability_description?: DisabilityDescription;
}
/**
 * Apribojimai - vairavimas, ginklai
 */
export interface Restrictions {
  cannot_drive?: CannotDrive;
  cannot_drive_date?: CannotDriveDate;
  cannot_use_weapon?: CannotUseWeapon;
}
/**
 * Alergijos įrašas - vaistams, maistui ar kitoms medžiagoms
 */
export interface Allergy {
  type: Type1;
  description: Description1;
  date?: Date1;
  source_segments?: SourceSegments4;
}
/**
 * Skiepų informacija
 */
export interface Vaccination {
  name: Name1;
  date?: Date2;
}
/**
 * Reference linking an extracted field to source transcript segments.
 */
export interface EntityReference {
  field_name: FieldName;
  value: Value1;
  source_segments: SourceSegments5;
  confidence?: Confidence;
}
